name: Publish to Firefox addon marketplace on Merge to main
on:
  workflow_dispatch:
  # pull_request:
  #   types: [closed]
  #   branches: [main, master]
    
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Zip the thing
        run: 7z a extension.zip manifest.json index.html scripts/* libs/*

      - name: publish to CWS
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: miuschedule2ics@danielmichel.developer
          xpi-path: extension.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}